<html>
    <head>
        <title> Login Admin </title>
          <link rel="stylesheet" href="/BaliJewelry1/public/css/admin.css">
        <body>
            <div class="login">
                <h1 class="text-center">Login</h1><br><br>
                <!--Login Form starts here -->
                <?php
                    if(isset($_SESSION['login'])) {
                        echo $_SESSION['login'];
                        unset($_SESSION['login']);
                    }
                ?>
                <form action="index.php?road=login" method="POST" class="text-center">
                    Username: <br>
                    <input type="text" name="username" placeholder="Enter username" required/><br><br>
                    Password: <br>
                    <input type="password" name="password" placeholder="Enter password" required/><br><br>
                    <input type="submit" name="submit" value="login" class="btn-primary"/>
                </form>
                <!--Login Form ends here -->
            </div>
        </body>
    </head>
</html>